spring:
  application:
    name: springboot
  datasource:
    url: jdbc:mysql://www.booleandev.xyz:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: root123456
    driver-classs-name: com.mysql.jdbc.Driver
server:
  port: 80



