spring:
  application:
    name: springboot
  profiles:
    active: dev
  freemarker:
    template-loader-path: ["classpath:/templates/"]
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml


